language: java
dist: trusty

# Skip the Travis CI's default install command
install: true

jdk:
  - openjdk8
  - openjdk11

script:
  # The CA Certs are outdated in JDK 7. Let's copy the ones from JDK 8
  - sudo mv /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/security/cacerts /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/security/cacerts.orig
  - sudo cp -t /usr/lib/jvm/java-7-openjdk-amd64/jre/lib/security /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/security/cacerts
  - ./mvnw clean verify -B -e -V

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.m2/wrapper'

branches:
    except:
        - gh-pages

notifications:
  email: true
